version: "3"

services:
  myapi:
    build: ./backend
    restart: always
    links:
      - mydb
    ports:
      - "5005:5005"
    networks:
      - flask_network
  

  mydb:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      ACCEPT_EULA: "Y"
      
    networks:
      - flask_network
    volumes:
      - ./Databases:/docker-entrypoint-mydb.d/
  front:
    build : ./frontend
    restart : always
    links :
      - mydb
      - myapi
    ports:
      - "3000:3000"
    networks:
      - flask_network
networks:
  flask_network:
    driver: bridge
volumes:
  Databases: